// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE-OARq5SV7urp5308WcWooLC1LQY3Zak',
    appId: '1:178818980665:web:be6ef4d521fe53cbcf66e8',
    messagingSenderId: '178818980665',
    projectId: 'test-50c29',
    authDomain: 'test-50c29.firebaseapp.com',
    storageBucket: 'test-50c29.appspot.com',
    measurementId: 'G-9BMLRXJMRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkxvXbogJTxr7bDuDFF9eAk_mhZ8VrVNg',
    appId: '1:178818980665:android:223b05c717537241cf66e8',
    messagingSenderId: '178818980665',
    projectId: 'test-50c29',
    storageBucket: 'test-50c29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwaeGsyN_ZAr0F6dyOpbld8VYeVVTMY-w',
    appId: '1:178818980665:ios:7fdc7f6264300e9dcf66e8',
    messagingSenderId: '178818980665',
    projectId: 'test-50c29',
    storageBucket: 'test-50c29.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwaeGsyN_ZAr0F6dyOpbld8VYeVVTMY-w',
    appId: '1:178818980665:ios:55ab0b8c17c8ae3bcf66e8',
    messagingSenderId: '178818980665',
    projectId: 'test-50c29',
    storageBucket: 'test-50c29.appspot.com',
    iosBundleId: 'com.example.todolistApp.RunnerTests',
  );
}
